"""Clinical escalation rules — hardcoded triggers from system prompt XML.

Implements escalation detection for:
- Life-threatening conditions
- Controlled substance requests
- Pediatric dosing concerns
- Pregnancy / teratogenicity flags
- Insufficient evidence fallback
"""

from __future__ import annotations

import re


# ---------------------------------------------------------------------------
# Escalation trigger constants
# ---------------------------------------------------------------------------

LIFE_THREATENING_KEYWORDS: list[str] = [
    "anaphylaxis", "anaphylactic",
    "cardiac arrest", "heart attack", "myocardial infarction",
    "stroke", "cerebrovascular accident",
    "pulmonary embolism",
    "sepsis", "septic shock",
    "respiratory failure", "respiratory arrest",
    "status epilepticus",
    "diabetic ketoacidosis", "DKA",
    "hyperosmolar hyperglycemic state", "HHS",
    "severe hypoglycemia", "hypoglycemic emergency",
    "aortic dissection",
    "tension pneumothorax",
    "hemorrhagic shock", "severe hemorrhage",
    "suicidal ideation", "suicide attempt", "self-harm",
    "overdose",
]

CONTROLLED_SUBSTANCE_KEYWORDS: list[str] = [
    "oxycodone", "hydrocodone", "morphine", "fentanyl", "codeine",
    "tramadol", "methadone", "buprenorphine", "oxymorphone",
    "hydromorphone", "meperidine",
    "alprazolam", "diazepam", "lorazepam", "clonazepam",
    "temazepam", "midazolam",
    "amphetamine", "methylphenidate", "dextroamphetamine",
    "lisdexamfetamine", "modafinil",
    "zolpidem", "zaleplon", "eszopiclone",
    "phenobarbital", "secobarbital",
    "pregabalin", "gabapentin",
    "testosterone", "anabolic steroid",
    "schedule II", "schedule III", "schedule IV",
    "controlled substance", "narcotic", "opioid prescription",
    "benzodiazepine prescription", "stimulant prescription",
]

PEDIATRIC_KEYWORDS: list[str] = [
    "pediatric", "child", "children", "infant", "neonate", "neonatal",
    "adolescent", "toddler", "newborn", "baby",
    "weight-based dosing", "mg/kg",
]

PREGNANCY_KEYWORDS: list[str] = [
    "pregnant", "pregnancy", "gestational", "prenatal", "trimester",
    "breastfeeding", "lactation", "lactating",
    "teratogenic", "teratogenicity",
    "possible pregnancy", "might be pregnant", "could be pregnant",
    "missed period", "positive pregnancy test",
    "fetal", "embryo",
]

INSUFFICIENT_EVIDENCE_MARKER: str = (
    "Insufficient guideline evidence. Clinician judgment required."
)

# Pre-compiled patterns for efficient matching
_LIFE_THREATENING_PATTERN: re.Pattern[str] = re.compile(
    r"\b(?:" + "|".join(re.escape(kw) for kw in LIFE_THREATENING_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

_CONTROLLED_SUBSTANCE_PATTERN: re.Pattern[str] = re.compile(
    r"\b(?:" + "|".join(re.escape(kw) for kw in CONTROLLED_SUBSTANCE_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

_PEDIATRIC_PATTERN: re.Pattern[str] = re.compile(
    r"\b(?:" + "|".join(re.escape(kw) for kw in PEDIATRIC_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

_PREGNANCY_PATTERN: re.Pattern[str] = re.compile(
    r"\b(?:" + "|".join(re.escape(kw) for kw in PREGNANCY_KEYWORDS) + r")\b",
    re.IGNORECASE,
)

# Pediatric age detection (e.g., "3 years old", "6 month old")
# Uses word boundary + captures only 1-2 digit numbers that aren't preceded by other digits
_PEDIATRIC_AGE_PATTERN: re.Pattern[str] = re.compile(
    r"(?<!\d)(\d{1,2})\s*(?:year|yr|month|mo)s?\s*old\b",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Escalation messages
# ---------------------------------------------------------------------------

ESCALATION_MESSAGES: dict[str, str] = {
    "life_threatening": (
        "⚠️ URGENT: Immediate clinician review required. "
        "A potentially life-threatening condition has been identified."
    ),
    "controlled_substance": (
        "⚠️ BLOCKED: This request involves a controlled substance. "
        "Controlled substance recommendations cannot be generated by this system. "
        "Please consult the prescribing provider directly."
    ),
    "pediatric_dosing": (
        "⚠️ PEDIATRIC FLAG: Weight-based verification required. "
        "Pediatric dosing must be verified by a pediatric specialist or pharmacist "
        "before any medication recommendation is acted upon."
    ),
    "pregnancy": (
        "⚠️ PREGNANCY FLAG: Teratogenicity review required. "
        "Pregnancy or possible pregnancy has been detected. All medication "
        "recommendations must be reviewed for teratogenic risk before acting."
    ),
}


def check_escalation(text: str) -> list[dict[str, str]]:
    """Check text for clinical escalation triggers.

    Args:
        text: The input text to scan for escalation triggers.

    Returns:
        List of triggered escalation rules, each containing:
        - 'trigger': The type of escalation (e.g., 'life_threatening')
        - 'message': The escalation message to prepend/return
        - 'matched': The specific keyword(s) that triggered the escalation
        - 'blocking': Whether this escalation should block response generation
    """
    triggers: list[dict[str, str]] = []

    # --- Life-threatening conditions ---
    match = _LIFE_THREATENING_PATTERN.search(text)
    if match:
        triggers.append({
            "trigger": "life_threatening",
            "message": ESCALATION_MESSAGES["life_threatening"],
            "matched": match.group(0),
            "blocking": "false",  # Urgent flag, but still generate advice
        })

    # --- Controlled substance requests ---
    match = _CONTROLLED_SUBSTANCE_PATTERN.search(text)
    if match:
        triggers.append({
            "trigger": "controlled_substance",
            "message": ESCALATION_MESSAGES["controlled_substance"],
            "matched": match.group(0),
            "blocking": "true",  # Block generation entirely
        })

    # --- Pediatric dosing ---
    if _PEDIATRIC_PATTERN.search(text):
        triggers.append({
            "trigger": "pediatric_dosing",
            "message": ESCALATION_MESSAGES["pediatric_dosing"],
            "matched": "pediatric keyword",
            "blocking": "false",
        })
    else:
        # Check for age-based pediatric detection
        age_match = _PEDIATRIC_AGE_PATTERN.search(text)
        if age_match:
            age_value = int(age_match.group(1))
            is_months = "month" in age_match.group(0).lower() or "mo" in age_match.group(0).lower()
            # Under 18 years or any month-based age
            if is_months or age_value < 18:
                triggers.append({
                    "trigger": "pediatric_dosing",
                    "message": ESCALATION_MESSAGES["pediatric_dosing"],
                    "matched": age_match.group(0),
                    "blocking": "false",
                })

    # --- Pregnancy / teratogenicity ---
    match = _PREGNANCY_PATTERN.search(text)
    if match:
        triggers.append({
            "trigger": "pregnancy",
            "message": ESCALATION_MESSAGES["pregnancy"],
            "matched": match.group(0),
            "blocking": "false",
        })

    return triggers
